### ISSUE TITLE
test fails with attribute error

### ISSUE THREAD

**Issue by adamist521** [c-bata/chalice-linebot#4]
Running `python -m unittest tests` fails with following code.
Any idea what going on?

```
(venv)********% python -m unittest tests
EEEEEE
======================================================================
ERROR: test_choice_when_items_separated_by_space (tests.ChoiceTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 24, in test_choice_when_items_separated_by_space
    actual = app._choice('choice a b').text
AttributeError: 'module' object has no attribute '_choice'

======================================================================
ERROR: test_choice_when_items_separated_by_space_with_UpperCharacter (tests.ChoiceTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 29, in test_choice_when_items_separated_by_space_with_UpperCharacter
    actual = app._choice('Choice a b').text
AttributeError: 'module' object has no attribute '_choice'

======================================================================
ERROR: test_echo_hello (tests.EchoTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 17, in test_echo_hello
    actual = app._echo('@bot Hello').text
AttributeError: 'module' object has no attribute '_echo'

======================================================================
ERROR: test_sleeping_greet (tests.GreetTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 10, in test_sleeping_greet
    actual = app._greet('眠たい').text
AttributeError: 'module' object has no attribute '_greet'

======================================================================
ERROR: test_shuffle_when_items_separated_by_space (tests.ShuffleTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 36, in test_shuffle_when_items_separated_by_space
    actual = app._shuffle('shuffle a b').text
AttributeError: 'module' object has no attribute '_shuffle'

======================================================================
ERROR: test_shuffle_when_items_separated_by_space_with_UpperCharacter (tests.ShuffleTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 41, in test_shuffle_when_items_separated_by_space_with_UpperCharacter
    actual = app._shuffle('Shuffle a b').text
AttributeError: 'module' object has no attribute '_shuffle'

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=6)
```

**Comment by c-bata** [comment]
Thank you. Fixed it!
